name: Frontend Deploy

on:
  push:
    branches: [ "main" ]


jobs:
  commit-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create new branch if it doesn't exist
      run: |
        git fetch origin
        if [ `git branch -r | grep "origin/gh-page" | wc -l` -eq 0 ]; then
          git checkout -b gh-page
        else
          git checkout gh-page
        fi

    - name: Copy file to new branch
      run: |
        echo "New content" > my-file.txt
        git add my-file.txt
        git commit -m "Add my-file.txt to gh-page"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin gh-page
